local_backend:
  url: http://localhost:8082/api/v1
  allowed_hosts: ["192.168.0.1"]

backend:
  name: git-gateway

media_folder: "public/media"
public_folder: "/media"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - label: "Podstrony"
    name: "pages"
    files:
      - label: "Strona główna"
        name: "home"
        file: "content/pages/homepage.md"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - {
              label: "Tagi",
              name: "tags",
              widget: "list",
              summary: "{{fields.tag}}",
              field: { label: "Tekst", name: "tag", widget: "string" },
            }
          - {
              label: "Tło",
              name: "backgroundImage",
              widget: "image",
              required: false,
            }

      - label: "Kontakt"
        name: "contact"
        file: "content/pages/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }

      - label: "Cennik"
        name: "price-list"
        file: "content/pages/price-list.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }

      - label: "Porfolio"
        name: "portfolio"
        file: "content/pages/portfolio.md"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - {
              label: "Paragrafy",
              name: "paragraphs",
              widget: "list",
              summary: "{{fields.paragraph}}",
              field: { label: "Tekst", name: "paragraph", widget: "text" },
            }

  - label: "Projekty"
    name: "projects"
    widget: "object"
    folder: "content/projects"
    create: true
    fields:
      - label: "Tytuł"
        name: "title"
        widget: "string"
      - label: "Opis"
        name: "description"
        widget: "text"
      - label: "Lokalizacja"
        name: "location"
        widget: "string"
        required: false
      - label: "Data"
        name: "date"
        widget: "string"
        required: false
      - label: "Typ projektu"
        name: "project_type"
        widget: "string"
        required: false
      - label: "Zdjęcia"
        name: "images"
        widget: "list"
        required: true
        summary: "{{fields.image}}"
        field: { label: "Obraz", name: "image", widget: "image" }

  - label: "Cenniki"
    name: "price-lists"
    widget: "object"
    folder: "content/price-list"
    create: true
    fields:
      - label: "Tytuł"
        name: "title"
        widget: "string"
      - label: "Opis"
        name: "description"
        widget: "text"
      - label: "Rodzaj"
        name: "type"
        widget: "select"
        options:
          - {label: "Pakiety podstawowe", value: "basic" }
          - {label: "Usługi dodatkowe", value: "additional"}
        default: "basic"
      - label: "Zdjęcie"
        name: "image"
        widget: "image"
      - label: "Oferta"
        name: "offer"
        widget: "list"
        fields:
          - label: "Tytuł"
            name: "title"
            widget: "text"
          - label: "Opis"
            name: "description"
            widget: "text"
          - label: "Odnośniki"
            name: "urls"
            multiple: true
            max: 2
            required: false
            widget: "relation"
            collection: "price-lists"
            search_fields: ["title", "description"]
            value_field: "{{slug}}__{{title}}"
            display_fields: ["title", "description"]
          - label: "Zdjęcie"
            name: "image"
            widget: "image"
            required: false

